config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   registrations: "registrations",
  #   sessions: "sessions"
  # }
  root to: "pages#home"
  get 'home', to: 'pages#home', as: :home
  get "about", to: "pages#about", as: :about
  get "random", to: "pages#random", as: :random
  get "search", to: "pages#search_form", as: :search
  get "tags_manage", to: "tags#manage", as: :tags_manage
  patch "home/reorder", to: "users#reorder", as: :reorder
  patch "/home/toggle_private", to: "lists#toggle_private", as: :toggle_private
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users do
    # patch "reorder", to: "users#reorder", as: :reorder
  end
  resources :vtubers do
    # patch :add_tag
  end
  patch "vtubers/:id/edit/add_tag", to: "vtubers#add_tag", as: :add_tag
  patch "vtubers/:id/edit/remove_tag", to: "vtubers#remove_tag", as: :remove_tag
  # resources :lists do
  #  resources :vtuber_markers, only: [:new, :create, :destroy]
  # end
  resources :lists do
    # get "reorder", to: "lists#reorder", as: :reorder
  end
  patch "lists/:id/sort", to: "lists#sort", as: :sort
  # patch "lists/:list_id/sort", to: "lists#sort", as: :list_id_sort

  resources :vtuber_markers do
    # patch "lists/:list_id/insert", to: "vtuber_markers#insert", as: :insert
  end
  resources :agencies

  # resources :vtuber_markers
  resources :list_markers
  resources :tags
  resources :submissions

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable,
  #        :trackable, authentication_keys: [:login]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # acts_as_favoritor


  # validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  has_many :lists, dependent: :destroy
  has_many :list_markers, dependent: :destroy
  has_one_attached :photo

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, uniqueness: true

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def lists
    List.where(user_id: id).order("position ASC")
  end

  def next_num
    List.where(user_id: id).length + 1
  end

  def self.find_by_name(name)
    User.where(username: name).first
  end

  def move_list(old_num, new_num)
    if old_num != new_num && old_num > 0 && old_num <= lists.length && new_num > 0 && new_num <= lists.length

      lists[old_num - 1].update(position: new_num)
      # target_list = lists[old_num - 1]

      # if new_num < old_num
      #   lists[new_num - 1..old_num - 2].each do |list|
      #     list.update(order_num: list.order_num + 1)
      #   end
      # elsif new_num > old_num
      #   lists[old_num..new_num - 1].each do |list|
      #     list.update(order_num: list.order_num - 1)
      #   end
      # end
      # target_list.update(order_num: new_num)
    end
  end

  def order
    lists.each do |list|
      puts "#{list.name}: #{list.position}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @lists = @user.lists
  end

  def reorder

    @user = User.find(params[:id])
    @user.move_list(params[:old_num].to_i, params[:new_num].to_i)
    redirect_to :home

  end

end

app/views/users/show.html.erb
<div style="display:flex; justify-content: center">
  <div class="user-show-container">
    <h2><%= @user.username %>'s Lists</h2>
    <% if user_signed_in? && current_user == @user %>
      <p><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "main-button" %></p>

      <% if current_user.role == "admin" %>
        <div class="admin-options">
          <h4>Admin only</h4>
          <%= link_to "Add VTuber Entry", new_vtuber_path, class: "main-button" %>
          <%= link_to "Add Agency Entry", new_agency_path, class: "main-button" %>
          <%= link_to "Manage Tags", :tags_manage, class: "main-button" %>
          <%= link_to "View Submissions", submissions_path, class: "main-button" %>
        </div>
      <% end %>
    <% end %>

    <div class="your-lists-header" style="display: flex; justify-content: end;">
      <% if user_signed_in? && current_user == @user %>
        <%= link_to new_list_path do %>
          <span class="main-button"><i class="fa-solid fa-file-circle-plus" style="align-self: center;"></i> Make a new list</span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

  <% if @lists.empty? %>
    <h5>This user has no lists</h5>
  <% elsif user_signed_in? && current_user == @user %>
    <%= render 'shared/current_user_lists', lists: @lists %>
  <% else %>
    <div class="home-list-container">
      <% @lists.each do |list| %>
        <% if !list.private || @user == current_user %>
          <div class="home-list-card">
            <div class="home-list-vtuber-row">

              <% list.get_vtuber_row.each do |vtuber| %>
                <div class="home-vtuber-card">
                  <div class="vtuber-card-pic">
                      <%= render "shared/vtuber_picture", vtuber: vtuber %>
                  </div>
                </div>
              <% end %>
            </div>

            <div class="home-list-name">
              <h4><%= list.name %></h4>
            </div>
            <div class="home-list-count">
              <p><i class="fa-solid fa-chalkboard-user" style="color: #ffffff;"></i> <%= list.vtuber_markers.length %></p>
            </div>


            <%= link_to list do %>
              <div class="click-box">
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>