config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   registrations: "registrations",
  #   sessions: "sessions"
  # }
  root to: "pages#home"
  get 'home', to: 'pages#home', as: :home
  get "about", to: "pages#about", as: :about
  get "random", to: "pages#random", as: :random
  get "search", to: "pages#search_form", as: :search
  get "tags_manage", to: "tags#manage", as: :tags_manage
  patch "home/reorder", to: "users#reorder", as: :reorder
  patch "/home/toggle_private", to: "lists#toggle_private", as: :toggle_private
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users do
    # patch "reorder", to: "users#reorder", as: :reorder
  end
  resources :vtubers do
    # patch :add_tag
  end
  patch "vtubers/:id/edit/add_tag", to: "vtubers#add_tag", as: :add_tag
  patch "vtubers/:id/edit/remove_tag", to: "vtubers#remove_tag", as: :remove_tag
  # resources :lists do
  #  resources :vtuber_markers, only: [:new, :create, :destroy]
  # end
  resources :lists do
    # get "reorder", to: "lists#reorder", as: :reorder
  end
  patch "lists/:id/sort", to: "lists#sort", as: :sort
  # patch "lists/:list_id/sort", to: "lists#sort", as: :list_id_sort

  resources :vtuber_markers do
    # patch "lists/:list_id/insert", to: "vtuber_markers#insert", as: :insert
  end
  resources :agencies

  # resources :vtuber_markers
  resources :list_markers
  resources :tags
  resources :submissions

end

app/views/shared/_current_user_lists.erb
<% if device =="desktop" %>
  <div id="<%= current_user.id %>" class="home-list-container" data-controller="list-sortable" >
<% else %>
  <div id="<%= current_user.id %>" class="home-list-container" >
<% end %>
      <% @lists.each do |list| %>
        <div id="<%= list.id %>" class="home-list-card" data-controller="home-options" >

          <div class="home-list-vtuber-row">

            <% list.get_vtuber_row.each do |vtuber| %>
              <div class="home-vtuber-card">
                <%# <div class="vtuber-card-pic"> %>
                    <%= render "shared/vtuber_picture", vtuber: vtuber %>
                <%# </div> %>
              </div>
            <% end %>
          </div>


              <div class="home-list-name">
                <h4><%= list.name %></h4>
              </div>
              <div class="home-list-count">
                <p><i class="fa-solid fa-chalkboard-user" ></i> <%= list.vtuber_markers.length %>

                  <% if list.private %>
                    <span id="private-icon" data-home-options-target="left_private_icon">
                      <i class="fa-solid fa-lock"></i>
                    </span>
                  <% else %>
                    <span id="private-icon" class="d-none" data-home-options-target="left_private_icon">
                      <i class="fa-solid fa-lock"></i>
                    </span>
                  <% end %>

                </p>
              </div>

              <div class="options-button" data-home-options-target="toggle_button" data-action="click->home-options#toggle_menu" >
                <i class="fa-solid fa-bars" ></i>
              </div>
              <div class="home-options-container d-none" data-home-options-target="menu" >
                <div class="home-options-menu" data-home-options-target="submenu1" >
                  <%= link_to edit_list_path(list), class:"options-link" do %>
                    <i class="fa-solid fa-pencil"></i> Rename this list
                  <% end %>
                  <%= link_to list_path(list),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" },
                  class: "options-link" do
                  %>
                    <i class="fa-solid fa-eraser"></i> Delete this list
                  <% end %>
                  <div data-home-options-target="private-button" data-action="click->home-options#private">
                    <%= form_with remote: true, url: :toggle_private, method: :patch do |f| %>
                      <%= f.hidden_field :id, value: list.id %>
                      <%= button_tag class: "private-button" do %>
                        <% if list.private %>
                          <span class="privated" data-home-options-target="right_private_icon">
                            <i class="fa-solid fa-lock"></i> Unprivate
                          </span>
                        <% else %>
                          <span class="unprivated" data-home-options-target="right_private_icon">
                            <i class="fa-solid fa-lock-open"></i> Private
                          </span>
                        <% end %>
                      <% end %>
                    <% end %>

                  </div>

                </div>

              </div>


          <%= link_to list do %>
            <div class="click-box">
            </div>
          <% end %>

        </div>
      <% end %>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer col-12">
  <div class="navbar-logo" >
    <%= link_to "VTuber List", :home, class: "navbar-logo" %>
  </div>
  <br>
  <strong>Sharing your oshis, made easy</strong>
  <p><strong>
    <%= link_to "About", :about, class: "footer-link" %>
    <%= link_to "Contribute", new_submission_path, class: "footer-link" %>
  </strong></p>
  <p>Beta Ver. 1.0</p>
</div>

app/views/shared/_list_display.html.erb
<% list.vtuber_markers.order(position: :asc).each do |marker| %>
  <div id="<%= marker.id %>" class="vtuber-card" data-controller="zoom-in" >
    <div class="vtuber-delete d-none" data-delete-button-target="button">
      <%= link_to vtuber_marker_path(marker),
        data: { turbo_method: :delete, turbo_confirm: "Delete this VTuber from this list?" } do %>
          <i class="fa-solid fa-square-xmark delete-icon"></i>
        <% end %>
    </div>

    <% if device =="desktop" %>
      <div class="vtuber-card-draggable" draggable="true">
    <% else %>
      <div class="vtuber-card-draggable">
    <% end %>
      <%= render "shared/vtuber_picture", vtuber: marker.vtuber %>
    </div>

    <div class="vtuber-card-body" data-action="mouseover->zoom-in#zoom_in mouseout->zoom-in#zoom_out" >
      <p><%= marker.vtuber.name %></p>
      <%= link_to vtuber_path(marker.vtuber) do %>
        <div class="click-box" data-delete-button-target="link">
        </div>
      <% end %>
      <div class="vtuber-card-footer" data-delete-button-target="link">
        <% if marker.vtuber.has_yt_channel? %>
          <%= link_to marker.vtuber.yt_channel, target: :blank do %>
            <i class="fa-brands fa-youtube" ></i>
          <% end %>
        <% end %>
        <% if marker.vtuber.has_twitch_channel? %>
          <%= link_to marker.vtuber.twitch_channel, target: :blank do %>
            <i class="fa-brands fa-twitch"></i>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="col-12">
  <nav class="navbar navbar-expand-lg">
    <div class="navbar-container" data-controller="dropdown">
      <div class="navbar-logo">
        <%= link_to "VTuber List", :home, class: "navbar-logo" %>
      </div>

      <div class="navbar-search">
        <div class="navbar-searchbar">
          <%= form_with url: vtubers_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form",
              placeholder: "Look for a VTuber"
              %>
            <%= submit_tag "Search", name: "", class:"search-button" %>
          <% end %>
          <%= link_to :search do %>
            <span class="main-button"><i class="fa-solid fa-magnifying-glass"></i> Advanced</span>
          <% end %>
        </div>
        <div class="search-buttons">
          <%= link_to agencies_path do %>
            <span class="main-button"><i class="fa-solid fa-building"></i> Search by agency</span>
          <% end %>
          <%= link_to tags_path do %>
            <span class="main-button"><i class="fa-solid fa-hashtag"></i> Search by tag</span>
          <% end %>
          <%= link_to :random do %>
            <span class="main-button"><i class="fa-solid fa-dice"></i> Get random VTubers</span>
          <% end %>
        </div>
      </div>

      <div class="navbar-user">
        <% if user_signed_in? %>
          <div class="username">
            <%= link_to user_path(current_user) do %>
              <span class="main-button">
              <i class="fa-solid fa-user-large"></i>
              <%= current_user.username %>
              </span>
            <% end %>
          </div>
          <div style="align-self: flex-end;">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "main-button" %>
          </div>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "main-button" %>
        <% end %>
      </div>

      <div class="navbar-button">
        <button class="navbar-toggler" type="button" data-action="click->dropdown#toggle" data-dropdown-target="button">
          <span class="navbar-toggler-icon toggle-button"></span>
        </button>
      </div>


      <div class="navbar-dropdown-menu dropdown-hidden d-none" data-dropdown-target="menu">
        <div class="dropdown-user dropdown-item">
          <% if user_signed_in? %>
            <div class="username">
              <%= link_to user_path(current_user) do %>
                <i class="fa-solid fa-user-large"></i>
                <%= current_user.username %>
              <% end %>
            </div>
            <div class= "dropdown-item" style="align-self: flex-end;">
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "main-button" %>
            </div>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "main-button" %>
          <% end %>
        </div>
        <div class="dropdown-searchbar dropdown-item">
          <%= form_with url: vtubers_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form",
              placeholder: "Look for a VTuber"
              %>
            <%= submit_tag "Search", name: "", class:"search-button" %>
          <% end %>
        </div>
        <%= link_to agencies_path do %>
          <span class="main-button dropdown-item"><i class="fa-solid fa-building"></i> Search by agency</span>
        <% end %>
        <%= link_to tags_path do %>
          <span class="main-button dropdown-item"><i class="fa-solid fa-hashtag"></i> Search by tag</span>
        <% end %>
        <%= link_to :random do %>
          <span class="main-button dropdown-item"><i class="fa-solid fa-dice"></i> Get random VTubers</span>
        <% end %>

      </div>

    </div>
  </nav>
</div>

app/views/shared/_unauthorized.html.erb
<p>You do not have permission to view this page. <i class="fa-regular fa-face-frown-open"></i></p>

app/views/shared/_vtuber_grid_display.erb
<div class="list-cards">
    <% @vtubers.each do |vtuber| %>
      <div class="vtuber-card" data-controller="zoom-in">

          <%= render "shared/vtuber_picture", vtuber: vtuber %>

        <div class="vtuber-card-body" data-action="mouseover->zoom-in#zoom_in mouseout->zoom-in#zoom_out">
          <p><%= vtuber.name %></p>
          <%= link_to vtuber_path(vtuber) do %>
            <div class="click-box">
            </div>
          <% end %>
          <div class="vtuber-card-footer">
            <% if vtuber.has_yt_channel? %>
              <%= link_to vtuber.yt_channel, target: :blank do %>
                <i class="fa-brands fa-youtube" ></i>
              <% end %>
            <% end %>
            <% if vtuber.has_twitch_channel? %>
              <%= link_to vtuber.twitch_channel, target: :blank do %>
                <i class="fa-brands fa-twitch" ></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/shared/_vtuber_picture.html.erb
<% if vtuber.thumbnail.attached? %>
  <div class="vtuber-card-pic" data-zoom-in-target="image">
    <%= cl_image_tag vtuber.thumbnail.key, crop: :thumb, gravity: :face, class: "vtuber-pic" %>
  </div>
<% elsif vtuber.photo_url && vtuber.photo_url != ""%>
  <div class="vtuber-card-pic" data-zoom-in-target="image">
    <%= image_tag vtuber.photo_url, class: "vtuber-pic" %>
  </div>
<% else %>
  <div data-zoom-in-target="image">
  </div>
  <div class="default-picture">
    <p><%= vtuber.name %></p>
  </div>

<% end %>