config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   registrations: "registrations",
  #   sessions: "sessions"
  # }
  root to: "pages#home"
  get 'home', to: 'pages#home', as: :home
  get "about", to: "pages#about", as: :about
  get "random", to: "pages#random", as: :random
  get "search", to: "pages#search_form", as: :search
  get "tags_manage", to: "tags#manage", as: :tags_manage
  patch "home/reorder", to: "users#reorder", as: :reorder
  patch "/home/toggle_private", to: "lists#toggle_private", as: :toggle_private
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users do
    # patch "reorder", to: "users#reorder", as: :reorder
  end
  resources :vtubers do
    # patch :add_tag
  end
  patch "vtubers/:id/edit/add_tag", to: "vtubers#add_tag", as: :add_tag
  patch "vtubers/:id/edit/remove_tag", to: "vtubers#remove_tag", as: :remove_tag
  # resources :lists do
  #  resources :vtuber_markers, only: [:new, :create, :destroy]
  # end
  resources :lists do
    # get "reorder", to: "lists#reorder", as: :reorder
  end
  patch "lists/:id/sort", to: "lists#sort", as: :sort
  # patch "lists/:list_id/sort", to: "lists#sort", as: :list_id_sort

  resources :vtuber_markers do
    # patch "lists/:list_id/insert", to: "vtuber_markers#insert", as: :insert
  end
  resources :agencies

  # resources :vtuber_markers
  resources :list_markers
  resources :tags
  resources :submissions

end

app/models/vtuber.rb
require "open-uri"

class Vtuber < ApplicationRecord
  acts_as_favoritable
  acts_as_favoritor

  scope :by_gender, -> gender { where(:gender => gender) }
  scope :by_language, -> language { where(:main_language => language)}
  scope :active, -> active { where(:active => active) }
  # scope :by_birthday, -> started_at, ended_at { where("started_at = ? AND ended_at = ?", started_at, ended_at) }

  belongs_to :agency
  has_many :vtuber_markers, dependent: :destroy
  has_many :tag_markers, dependent: :destroy
  has_many :group_markers, dependent: :destroy
  has_many :tags, through: :tag_markers, source_type: "Tag"
  has_many :groups, through: :group_markers, source_type: "Group"
  has_many_attached :photos
  has_one_attached :thumbnail
  has_one_attached :vertical_picture

  validates :name, presence: true
  validates :description, presence: true
  validates_uniqueness_of :name, scope: :agency

  include PgSearch::Model
  pg_search_scope :search_by_name,
  against: [ :name, :jp_name, :main_language ],
  associated_against: {
    agency: [:name]
  },
  using: {
    tsearch: { prefix: true }
  }

  include PgSearch::Model
  pg_search_scope :search_by_gender,
  against: [ :gender ],
  using: {
    tsearch: { prefix: true }
  }


  def self.find_by_name(name)
    Vtuber.where(name: name).first
  end

  def get_birthday
    if birthday
      birthday.strftime("%B %-d")
    else
      "Not available"
    end
  end

  def get_debut_date
    if debut_date
      debut_date.strftime("%B %-d, %Y")
    else
      "Not available"
    end
  end

  def tags
    arr = []
    TagMarker.where(vtuber_id: id).each do |tm|
      arr << Tag.find(tm.tag_id)
    end
    return arr
  end

  def tag_names
    arr = []
    TagMarker.where(vtuber_id: id).each do |tm|
      arr << Tag.find(tm.tag_id).name
    end
    return arr
  end

  def add_tag(tag_name)
    tm = TagMarker.new
    tm.vtuber_id = id
    tm.tag = Tag.where(name: tag_name).first

    return tm.save
  end

  def remove_tag(tag_name)
    TagMarker.where(vtuber_id: id).each do |tm|
      if Tag.find(tm.tag_id).name == tag_name
        return tm.destroy!
      end
    end
  end

  def remove_all_tags
    puts("Removing #{name}'s tags}")
    TagMarker.where(vtuber_id: id).each do |tm|
      tm.destroy!
      puts("Removed #{Tag.find(tm.tag_id).name}")
    end
  end

  def addable_tags
    current_tags = tags
    arr = []

    Tag.all.order('LOWER(name)').each do |tag|
      if !current_tags.include?(tag)
        arr << tag.name
      end
    end

    return arr
  end


  def has_tag?(tag_name)
    tms = TagMarker.where(vtuber_id: id)
    tms.each do |tm|
      if tm.tag.name.downcase == tag_name.downcase
        return true
      end
    end
    return false
  end

  def has_jp_name?
    (jp_name && jp_name != "")
  end

  def has_website?
    website && !website.blank?
  end

  def has_yt_channel?
    yt_channel && !yt_channel.blank?
  end

  def has_twitch_channel?
    twitch_channel && !twitch_channel.blank?
  end

  def num_of_people_tagged
    count = 0
    arr = []
    tms = VtuberMarker.where(vtuber_id: id)
    tms.each do |tm|
      puts tm.list.name
      if !arr.include?(tm.list.user)
        arr << tm.list.user
        count += 1
      end
    end
    return count
  end

  def self.get_random_vtuber
    Vtuber.all.sample
  end

  def set_thumbnail(url)
    file = URI.parse(url).open
    thumbnail.attach(
    io: file,
    filename: "thumbnail.png",
    content_type: "image/png"
    )
    return save
  end

  def set_vertical_picture(url)
    file = URI.parse(url).open
    vertical_picture.attach(
    io: file,
    filename: "vertical_picture.png"
    )
    return save
  end


end

app/controllers/vtubers_controller.rb
class VtubersController < ApplicationController



  def index
    @vtubers = []
    # raise
    if params[:query].present?
      @vtubers = Vtuber.search_by_name(params[:query])
    end
  end


  def new
    @vtuber = Vtuber.new
    @agencies = Agency.all.order('LOWER(name)')
  end

  def create
    @vtuber = Vtuber.new(vtuber_params)
    if @vtuber.save
      redirect_to vtuber_path(@vtuber)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @vtuber = Vtuber.find(params[:id])
    # current user's lists that do not include VTuber
    @lists = []
    if user_signed_in?
      current_user.lists.each do |list|
        if !list.has_vtuber?(@vtuber)
          @lists << list
        end
      end
    end

    @list = List.new
    @marker = VtuberMarker.new
    # @tag = Tag.new
    # @tags = Tag.all
  end

  def edit
    @vtuber = Vtuber.find(params[:id])
    @agencies = Agency.all.order('LOWER(name)')
    @tags = @vtuber.addable_tags
    @current_tags = @vtuber.tags
  end

  def update
    @vtuber = Vtuber.find(params[:id])
    if @vtuber.update(vtuber_params)
      redirect_to vtuber_path(@vtuber)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def search
    @vtubers = []
    raise
    if params[:query].present?
      @vtubers = Vtuber.search_by_name(:query)
    end
    raise
  end

  def add_tag

    @vtuber = Vtuber.find(params[:id])
    @vtuber.add_tag(params[:tag_name])
    # @vtuber.favorite()

    redirect_to vtuber_path(@vtuber)
  end

  def remove_tag
    @vtuber = Vtuber.find(params[:id])
    @vtuber.remove_tag(params[:tag_name])

    redirect_to vtuber_path(@vtuber)
  end

  def destroy
    @vtuber = Vtuber.find(params[:id])
    @vtuber.destroy!
    redirect_to :home
  end

  private

  def vtuber_params
    params.require(:vtuber).permit(
      :name,
      :jp_name,
      :description,
      :agency_id,
      :yt_channel,
      :twitch_channel,
      :photo_url,
      :gender,
      :birthday,
      :debut_date,
      :main_language,
      :active,
      :thumbnail,
      :vertical_picture,
      photos: []
    )
  end
end

app/views/vtubers/edit.html.erb
<div class="container col-12 col-lg-6">
  <% if !(user_signed_in? && current_user.role == "admin") %>
    <%= render "shared/unauthorized" %>
  <% else %>
    <h2>Edit VTuber</h2>
    <%= simple_form_for(@vtuber) do |f| %>
      <%= f.input :name %>
      <%= f.input :jp_name, label: "JP name" %>
      <%= f.association :agency, collection: @agencies %>
      <%= f.input :gender, collection: ["female", "male", "neutral"] %>
      <%= f.input :birthday, discard_year: true, discard_time: true, include_blank: true %>
      <%= f.input :debut_date, start_year: Date.current.year+1, end_year: 1970, include_blank: true %>
      <%= f.input :description, as: :text %>
      <%= f.input :main_language %>
      <%= f.input :yt_channel, label: "YouTube channel" %>
      <%= f.input :twitch_channel %>
      <%= f.input :active, as: :boolean %>
      <%= f.input :thumbnail, as: :file %>
      <%= f.input :vertical_picture, as: :file %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>


      <%#= f.input :photos, as: :file, input_html: { multiple: true } %>
      <div class="form-actions">
        <%= f.button :submit, class:"btn-create" %>
      </div>

      <%# <h2>Add tags</h2> %>

    <% end %>

    <div class="add-tags-container">
      <h2>Add Tags</h2>
      <% if !@vtuber.addable_tags.empty? %>
        <%= form_with url: :add_tag, method: :patch do |f| %>
          <%= f.select :tag_name, @vtuber.addable_tags %>
          <%= f.submit :submit, label: "Add tag" %>
        <% end %>
      <% end %>
      <h2>Remove Tags</h2>
      <% if @vtuber.tag_names.empty? %>
        <p>This VTuber has no tags.</p>
      <% else %>
        <%= form_with url: :remove_tag, method: :patch do |f| %>
          <%= f.select :tag_name, @vtuber.tag_names %>
          <%= f.submit :submit, label: "Remove tag" %>
        <% end %>
      <% end %>
    </div>

    <%# <div class="vtuber-delete"> %>
      <%= link_to vtuber_path(@vtuber),
      data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this VTuber?" }, class: "delete-btn" do %>
      Delete this VTuber
      <% end %>
    <%# </div> %>

  <% end %>
</div>

app/views/vtubers/index.html.erb
<div style="display:flex; justify-content: center;">
  <div class="list-show-container">
    <div class="search-header">
      <h2>Search results</h2>
      <div >
        <% if @vtubers.empty? %>
          <div style="display: flex; justify-content: center">
            <p>No VTubers matched your search</p>
          </div>
        <% elsif @vtubers.length == 1 %>
          <p><span class="search-result-number">1</span> search result</p>
        <% else %>
          <p><span class="search-result-number"><%= @vtubers.length %></span> search results</p>
        <% end %>
      </div>
    </div>
    <div class="list-cards-container">
      <div class="list-cards">
        <% @vtubers.order('LOWER(name)').each do |vtuber| %>
          <div class="vtuber-card" data-controller="zoom-in">

            <%= render "shared/vtuber_picture", vtuber: vtuber %>

            <div class="vtuber-card-body" data-action="mouseover->zoom-in#zoom_in mouseout->zoom-in#zoom_out">
              <p><%= vtuber.name %></p>
              <%= link_to vtuber_path(vtuber) do %>
                <div class="click-box">
                </div>
              <% end %>
              <div class="vtuber-card-footer">
                <% if vtuber.has_yt_channel? %>
                  <%= link_to vtuber.yt_channel, target: :blank do %>
                    <i class="fa-brands fa-youtube" ></i>
                  <% end %>
                <% end %>
                <% if vtuber.has_twitch_channel? %>
                  <%= link_to vtuber.twitch_channel, target: :blank do %>
                    <i class="fa-brands fa-twitch" ></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/vtubers/new.html.erb
<div class="container col-6">
<% if !(user_signed_in? && current_user.role == "admin") %>
    <%= render "shared/unauthorized" %>
  <% else %>
    <h2>Make New VTuber Entry</h2>
    <%= simple_form_for(@vtuber) do |f| %>
      <%= f.input :name %>
      <%= f.input :jp_name, label: "JP name" %>
      <%= f.association :agency, collection: @agencies %>
      <%= f.input :gender, collection: ["female", "male", "neutral"] %>
      <%= f.input :birthday, discard_year: true, discard_time: true, include_blank: true %>
      <%= f.input :debut_date, start_year: Date.current.year+1, end_year: 1970, include_blank: true %>
      <%= f.input :description, as: :text %>
      <%= f.input :main_language %>
      <%= f.input :yt_channel, label: "YouTube channel" %>
      <%= f.input :twitch_channel %>
      <%= f.input :thumbnail, as: :file %>
      <%= f.input :vertical_picture, as: :file %>
      <%= f.input :active, as: :boolean %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>


      <%#= f.input :photos, as: :file, input_html: { multiple: true } %>
      <div class="form-actions">
        <%= f.button :submit, class:"btn-create" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/vtubers/search.html.erb
<div class="container col-6">
  <h2>Search results</h2>
</div>

app/views/vtubers/show.html.erb
<div class="page-container">
  <div class="list-show-container">
    <div style="position: relative;">
      <div class="edit-button-container">
      <% if user_signed_in? && current_user.role == "admin" %>
        <div class="edit-button"><%= link_to "Edit VTuber info", edit_vtuber_path %></div>
      <% end %>
      </div>
      <div class="vtuber-show-container">
        <div class="vtuber-show-picture-card">

          <% if @vtuber.vertical_picture.attached? %>
            <%= cl_image_tag @vtuber.vertical_picture.key, class: "vtuber-tall-picture" %>

          <% elsif @vtuber.photo_url %>
            <%= image_tag @vtuber.photo_url, class: "vtuber-tall-picture" %>
          <% end %>
        </div>
        <div class="vtuber-show-body">
          <div class="badge-group">
            <h3><span class="fw-bold show-card-name"><%= @vtuber.name %></span></h3>
            <% if @vtuber.has_jp_name? %>
              <h5><span class="show-card-name"><%= @vtuber.jp_name %></span></h5>
            <% end %>
            <h3>
            <% if @vtuber.has_yt_channel?  %>
              <%= link_to @vtuber.yt_channel, target: :blank do %>
                <i class="fa-brands fa-youtube" ></i>
              <% end %>
            <% end %>
            <% if @vtuber.has_twitch_channel? %>
              <%= link_to @vtuber.twitch_channel, target: :blank do %>
                <i class="fa-brands fa-twitch" ></i>
              <% end %>
            <% end %>
            </h3>
          </div>
          <div class="vtuber-show-card-content">
            <p><span class="btn agency-button"><%= link_to @vtuber.agency.name, agency_path(@vtuber.agency) %></span></p>
            <div class="vtuber-show-card-info">
              <table>
                <tr>
                  <td><strong>Gender:</strong></td>
                  <% if @vtuber.gender %>
                    <td><%= @vtuber.gender.capitalize %></td>
                  <% end %>
                </tr>
                <tr>
                  <td><strong>Main language:</strong></td>
                  <td><%= @vtuber.main_language %></td>
                </tr>
                <tr>
                  <td><strong>Birthday:</strong></td>
                  <td><%= @vtuber.get_birthday %></td>
                </tr>
                <tr>
                  <td><strong>Debut date:</strong></td>
                  <td><%= @vtuber.get_debut_date %></td>
                </tr>
              </table>
                <% if !@vtuber.active %>
                  <p><%= @vtuber.name %> is not active.</p>
                <% end %>
            </div>
            <p style="white-space: pre-line;"><%= @vtuber.description %></p>
          </div>
        </div>
      </div>
      <div class="vtuber-show-footer">
        <div class="vtuber-show-tags">
          <h4>Tags</h4>
          <% @vtuber.tags.each do |tag| %>
            <span class="btn tag-button"><%= link_to tag.name, tag_path(tag) %></span>
          <% end %>
          </div>
        </div>
        <div class="vtuber-show-add">
          <% if !user_signed_in? %>
            <h5><%= link_to "Log in", new_user_session_path, class: "main-button" %> to add this VTuber to a list</h5>
          <% elsif @lists.empty? %>
            <h5><%= link_to "Make a new list", new_list_path, class: "main-button" %> to add this VTuber</h5>
          <% else %>
            <%# <p>You have this VTuber in this list:</p> %>
            <h4>Add this VTuber to a list</h4>
            <div class="add-vtuber-form">
              <%= simple_form_for @marker do |f| %>
                <%= f.hidden_field :vtuber_id, value: Vtuber.find(params[:id]).id %>
                <%= f.association :list, collection: @lists, label: false %>
                <div class="form-actions">
                <%= button_tag type: "submit", class: "btn submit-button" do %>
                  <i class="fa-solid fa-plus"></i> Add VTuber
                <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>