config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   registrations: "registrations",
  #   sessions: "sessions"
  # }
  root to: "pages#home"
  get 'home', to: 'pages#home', as: :home
  get "about", to: "pages#about", as: :about
  get "random", to: "pages#random", as: :random
  get "search", to: "pages#search_form", as: :search
  get "tags_manage", to: "tags#manage", as: :tags_manage
  patch "home/reorder", to: "users#reorder", as: :reorder
  patch "/home/toggle_private", to: "lists#toggle_private", as: :toggle_private
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :users do
    # patch "reorder", to: "users#reorder", as: :reorder
  end
  resources :vtubers do
    # patch :add_tag
  end
  patch "vtubers/:id/edit/add_tag", to: "vtubers#add_tag", as: :add_tag
  patch "vtubers/:id/edit/remove_tag", to: "vtubers#remove_tag", as: :remove_tag
  # resources :lists do
  #  resources :vtuber_markers, only: [:new, :create, :destroy]
  # end
  resources :lists do
    # get "reorder", to: "lists#reorder", as: :reorder
  end
  patch "lists/:id/sort", to: "lists#sort", as: :sort
  # patch "lists/:list_id/sort", to: "lists#sort", as: :list_id_sort

  resources :vtuber_markers do
    # patch "lists/:list_id/insert", to: "vtuber_markers#insert", as: :insert
  end
  resources :agencies

  # resources :vtuber_markers
  resources :list_markers
  resources :tags
  resources :submissions

end

app/models/submission.rb
class Submission < ApplicationRecord
  has_many_attached :thumbnail
  has_many_attached :vertical_picture
  validates :name, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
    @submission = Submission.find(params[:id])
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
    @agencies = Agency.names

  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to new_submission_path, notice: "Your submission was sent!" }
        format.json { render :new, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy!

    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      # params.fetch(:submission, {})
      params.require(:submission).permit(
        :name,
        :jp_name,
        :description,
        :agency,
        :yt_channel,
        :twitch_channel,
        :gender,
        :birthday,
        :debut_date,
        :main_language,
        :active,
        :thumbnail,
        :vertical_picture,
        :comment,
        :website,
        :location,
        :submission_type,
        tags: []
      )
    end
end

app/views/submissions/_agency_form.html.erb
<%= simple_form_for(@submission) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <h3>Agency Submissions</h3>
  <p>Submit a new agency or suggest a change to an existing agency entry.<br>
     If you want to suggest a change, enter the agency's name, put in whatever change you want, and leave the rest blank.</p>
  <div class="form-inputs">

    <%#= f.hidden_field :type, value: "VTuber" %>
    <%= f.hidden_field :submission_type, value: "agency" %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :location %>
    <%= f.input :website %>
    <%= f.input :yt_channel, label: "YouTube channel" %>
    <%= f.input :active, as: :boolean, input_html: {checked: true} %>
    <%= f.input :comment, label: "Comments" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-create" %>
  </div>
<% end %>

app/views/submissions/_form.html.erb
<%= simple_form_for(@submission) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <h3>VTuber Submissions</h3>
  <p>Submit a new VTuber or suggest a change to an existing VTuber entry.<br>
     If you want to suggest a change, enter the VTuber's name, put in whatever change you want, and leave the rest blank.</p>
  <div class="form-inputs">

    <%= f.hidden_field :submission_type, value: "vtuber" %>
    <%= f.input :name %>
    <%= f.input :agency %>
    <p><span style="margin-right: 10px;"><%= f.radio_button :gender, 'female' %> Female</span>
      <span style="margin-right: 10px;"><%= f.radio_button :gender, 'male' %> Male</span>
      <span style="margin-right: 10px;"><%= f.radio_button :gender, 'other' %> Other</p></span>
      <%= f.input :birthday, discard_year: true, discard_time: true %>
      <%= f.input :debut_date, start_year: 1970 %>
      <%= f.input :description, as: :text %>
      <%= f.input :main_language %>
      <%= f.input :yt_channel, label: "YouTube channel" %>
      <%= f.input :twitch_channel %>
      <%= f.input :active, as: :boolean, input_html: {checked: true} %>
      <%= f.input :thumbnail, as: :file %>
      <%= f.input :vertical_picture, as: :file, label: "Full Body Picture" %>
      <%= f.input :comment, label: "Comments" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-create" %>
  </div>
<% end %>

app/views/submissions/_submission.html.erb
<div id="<%= dom_id submission %>">
  <%= submission.id %>
  <%= submission.name %>
</div>

app/views/submissions/_tag_form.html.erb
<%= simple_form_for(@submission) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <h3>Tag Submissions</h3>
  <p>Suggest a new tag that's not already here.</p>
  <div class="form-inputs">

    <%#= f.hidden_field :type, value: "VTuber" %>
    <%= f.input :name %>
    <%= f.input :comment, label: "Comments" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-create" %>
  </div>
<% end %>

app/views/submissions/_vtuber_form.html.erb
<%= simple_form_for(@submission) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <h3>VTuber Submissions</h3>
  <p>Submit a new VTuber or suggest a change to an existing VTuber entry.<br>
     If you want to suggest a change, enter the VTuber's name, put in whatever change you want, and leave the rest blank.</p>
  <div class="form-inputs">

    <%= f.hidden_field :submission_type, value: "vtuber" %>
    <%= f.input :name %>
    <%= f.input :agency %>
    <p><span style="margin-right: 10px;"><%= f.radio_button :gender, 'female' %> Female</span>
      <span style="margin-right: 10px;"><%= f.radio_button :gender, 'male' %> Male</span>
      <span style="margin-right: 10px;"><%= f.radio_button :gender, 'other' %> Other</p></span>
      <%= f.input :birthday, discard_year: true, discard_time: true %>
      <%= f.input :debut_date, start_year: 1970 %>
      <%= f.input :description, as: :text %>
      <%= f.input :main_language %>
      <%= f.input :yt_channel, label: "YouTube channel" %>
      <%= f.input :twitch_channel %>
      <%= f.input :active, as: :boolean, input_html: {checked: true} %>
      <%= f.input :thumbnail, as: :file %>
      <%= f.input :vertical_picture, as: :file, label: "Full Body Picture" %>
      <%= f.input :comment, label: "Comments" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn-create" %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Show this submission", @submission %> |
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/index.html.erb
<div class="container col-12 col-lg-6">
  <p style="color: green"><%= notice %></p>

  <h2>Submissions</h2>

  <div id="submissions">
    <% @submissions.each do |submission| %>
      <%= render submission %>
      <p>
        <%= link_to "Show this submission", submission %>
      </p>
    <% end %>
  </div>

  <%= link_to "New submission", new_submission_path %>
</div>

app/views/submissions/new.html.erb
<div class="page-container">
  <div class="devise-container">
    <div>
      <h2>Want to Add a VTuber?</h2>
    </div>
    <p style="color: green"><%= notice %></p>
    <div>
      <p>If there's a VTuber or agency that's not on VTuber List, submit them here.<br>
      If there's a page that's missing information or a picture, submit them here.<br>
      If you want to suggest changes to a VTuber's page, submit them here.<br>
      Contribute to VTuber List, make your oshi known, and make my job easier.<br>
    </div>
    <div data-controller="submission">

      <div style="margin: 25px 0 25px 0;">
        <p>I want to suggest a:</p>
          <%#= f.select :type, [["VTuber", "VTuber"], ["Agency", "Agency"], ["Tag", "Tag"]], selected: "VTuber" %>
          <%# <span data-submission-target="menu"><%= select_tag(:type, options_for_select([["VTuber", "VTuber"], ["Agency", "Agency"], ["Tag", "Tag"]])) %>
          <div class="submission-tab-bar">
            <div class="submission-tab submission-selected" data-submission-target="vtuber_tab">
              <span class="tab-inner" data-action="click->submission#open_vtuber_form" >VTuber</span>
            </div>
            <div class="submission-tab" data-submission-target="agency_tab">
              <span class="tab-inner" data-action="click->submission#open_agency_form" >Agency</span>
            </div>
            <%# <div class="submission-tab" data-submission-target="tag_tab">
              <span class="tab-inner" data-action="click->submission#open_tag_form">Tag</span>
            </div> %>
          </div>
      </div>
      <div data-submission-target="vtuber_form">
        <%= render "vtuber_form" %>
      </div>
      <div data-submission-target="agency_form" class="d-none">
        <%= render "agency_form" %>
      </div id="agency_form">
    </div>
  </div>
</div>

app/views/submissions/show.html.erb
<div class="container col-12 col-lg-6">
  <% if !(user_signed_in? && current_user.role == "admin") %>
    <%= render "shared/unauthorized" %>
  <% else %>

    <p style="color: green"><%= notice %></p>

    <%= render @submission %>

    <div>
      <%= link_to "Edit this submission", edit_submission_path(@submission) %> |
      <%= link_to "Back to submissions", submissions_path %>

      <%= button_to "Destroy this submission", @submission, method: :delete %>
    </div>
  <% end %>
</div>